### ISSUE TITLE
Move color definition to constructor

### ISSUE THREAD

**Issue by kfarr** [dbradleyfl/aframe-gridhelper#2]
Using new aframe 0.4.0 i get this error:
`three.js:40066 THREE.GridHelper: setColors() has been deprecated, pass them in the constructor instead.`

I did a quick fork to fix this (passing colors as part of the constructor now):
https://github.com/kfarr/aframe-gridhelper

however i am not able to get this to work with aframe 0.4.0 yet, it only shows 2 lines of the bounding box and no internal grid lines so i'm not going to do a pull request until that issue is resolved

**Comment by dbradleyfl** [comment]
#3
